Feature#7/create the landing page
BC-MAY-21-ROR/proyecto-final-pf-f22-t4 pull request #11
Opened 2022-04-19 23:56 UTC by brocha05

# Description
What did you implemented/Why did you implemented this:
- We created the landing page including
- We configured SASS pattern to work with
- We build the partials for navbar and footer 
- We add example images 
  
  ## Screenshots 
![image](https://user-images.githubusercontent.com/87162540/164119826-3fe07afe-9c2f-4153-a89a-991b41f6eb6c.png)

2022-04-20 13:45 UTC, dannharo commented on .gitignore
> +# Ignore all logfiles and tempfiles.
remove this extra space and also add the 
`**/.DS_Store` to ignore all the Binary file added in this `PR`

2022-04-20 13:45 UTC, dannharo commented on app/assets/stylesheets/abstracts/_clases.scss
> +.logo {
there is a typo in the name of this file, `classes` instead of `clases` to keep all the names in english

2022-04-20 13:45 UTC, dannharo commented on app/assets/stylesheets/abstracts/_mixins.scss
> +@mixin center-flex-column {
good job using mixins 👍🏻

2022-04-20 13:45 UTC, dannharo commented on app/assets/stylesheets/abstracts/_variables.scss
> +$text-grey:hsl(0, 1%, 26%);
add the space after the `colon` `$text-grey: hsl(0, 1%, 26%);`

2022-04-20 13:45 UTC, dannharo commented on app/assets/stylesheets/abstracts/_variables.scss
> +$shadow-grey:hsla(0, 1%, 26%, 0.37);
also here

2022-04-20 13:45 UTC, dannharo commented on app/views/layouts/_footer.html.erb
> +            ¡Cuidando perros desde el renacentismo pa!
🐶

2022-04-20 20:17 UTC, brocha05 commented on .gitignore
> +# Ignore all logfiles and tempfiles.
Changes made

2022-04-21 17:42 UTC, JuanequeX requested changes

2022-04-21 17:42 UTC, JuanequeX commented on app/assets/stylesheets/components/_footer.scss
> +    color: white;
use a variable to add this color!

2022-04-21 17:42 UTC, JuanequeX commented on app/assets/stylesheets/components/_footer.scss
> +            color: white;
Use a variable to add this color!

2022-04-21 17:42 UTC, JuanequeX commented on app/assets/stylesheets/views/_home.scss
> +    background-color: white;
Use a variable to add this color!

2022-04-21 17:42 UTC, JuanequeX commented on app/assets/stylesheets/views/_home.scss
> +    box-shadow: 0px 0px 5px black;
Same observation here, please use a variable to color black in your file _variables.scss

2022-04-21 20:30 UTC, brocha05 commented on app/assets/stylesheets/components/_footer.scss
> +    color: white;
Changes made

2022-04-21 23:08 UTC, alexs approved these changes
LGTM nice good job

2022-04-21 23:08 UTC, MrCano369x approved these changes
LGTM

2022-04-21 23:36 UTC, merged